config/routes.rb
Pinteresting::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about"
  get "mystical_cat_pics" => "pages#mystical_cat_pics"

end

app/models/pin.rb
class Pin < ActiveRecord::Base

  belongs_to :user
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
  #attr_accessible :image_file_name
  #attr_accessor :image_file_name
  #attr_accessor :image_content_type
  #attr_accessor :image_file_size
  #attr_accessor :image_updated_at
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
		 
  has_many :pins
		 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
	
  def mystical_cat_pics
  end
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy] 
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all
  end

  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)   
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'      
    else
      render action: 'new'  
    end    
  end

  def update   
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'         
    else
      render action: 'edit'        
    end
  end

  def destroy
    @pin.destroy  
    redirect_to pins_url      
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end
	
	def correct_user
	  @pin = current_user.pins.find_by(id: params[:id])
	  redirect_to pins_path, notice: "do not try to edit/delete other people's pins" if @pin.nil?
	end
	

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
		<div class="container">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to "Mystical Cats", root_path, class: "navbar-brand" %>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Mystical Cat Pics", mystical_cat_pics_path %></li>
					<li><%= link_to 'Pics', pins_path %></li>
					<% if user_signed_in? %>
					  <li><%= link_to new_pin_path do%>
						<span class="glyphicon glyphicon-plus"></span> Upload Pic
					  <% end %></li>
					  <li><%= link_to "Account Settings", edit_user_registration_path %></li>
					  <%= link_to "Log Out", destroy_user_session_path, class: "btn btn-primary", id: "log-out", method: :delete %>
					<% else %>
					  <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary", id: "log-in" %>
					<% end %>	
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container -->
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pinteresting</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg|%>
			<%= content_tag(:div, msg, class: "alert alert-info")%>
		<% end %>
	  <%= yield %>
   </div>
</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron">
	<h1>Welcome to my app</h1>
		
	<% if user_signed_in? %>
	  <p>Time to check out some sweet cat pics!</p>
	<% else %>	
		<p>Where you can look at mystical cat pics! <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %></p>
	<% end %>	
		
</div>

app/views/pages/about.html.erb
<div class="jumbotron">
	<h1>About Site</h1>
	<p>This site is dedicated to Josh Bensing and his love of mystical cats.</p>
	<p>Check out some mystical cat pictures below!</p>
	<%= link_to "Show me the mystical cat pics!", "http://localhost:3000/mystical_cat_pics", class: "btn btn-primary btn-lg" %>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	<h1>Welcome to my app</h1>
		
	<% if user_signed_in? %>
	  <p>Time to check out some sweet cat pics!</p>
	<% else %>	
		<p>Where you can look at mystical cat pics! <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %></p>
	<% end %>	
		
</div>

app/views/pages/mystical_cat_pics.html.erb
<div class="jumbotron">
	<h1>These cats are totes cray!</h1>
	<img src="http://images2.layoutsparks.com/1/100485/mystic-creature-tiger-animal.jpg' alt='mystic creature tiger animal pictures, backgrounds and images' title='mystic creature tiger animal pictures, backgrounds and images" height="160" width="200">
	<img src="http://image.blingee.com/images15/content/output/000/000/000/441/284440909_1972661.gif" height="160" width="200">
	<img src="http://www.grandmidwayhotel.com/wp-content/uploads/2012/11/Egypt.jpg" height="160" width="200">
	<img src="http://fc04.deviantart.net/fs70/f/2011/063/b/c/mystical_cat_by_sargeraas-d3avfup.jpg" height="160" width="200">
	<img src="http://cache.desktopnexus.com/thumbnails/242115-bigthumbnail.jpg" height="160" width="200">
</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<% unless user_signed_in? %>
  <%= render 'pages/home' %>
<% else %>
	<div id="pins" class="transitions-enabled">
		<% @pins.each do |pin| %>
		  <div class="box panel panel-default">	
			<%= link_to image_tag(pin.image.url(:medium)), pin %> 
			<div class="panel-body" id="pin-label">
			  <div class="actions">
				<%= pin.description %>
			  </div>	
			  <strong><%= pin.user.email if pin.user %></strong>
			  <% if pin.user == current_user && user_signed_in? %>
				<div class="actions">
				<%= link_to edit_pin_path(pin) do%> 
				  <span class="glyphicon glyphicon-wrench"></span>Edit
				<% end %>
				<%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
				  <span class="glyphicon glyphicon-trash", id="remove-glyphicon"></span>Remove
				<% end %>  
				</div>
			  <% end %>
			</div>		  
		  </div>	
		<% end %>
	</div>
<% end %>   

  
  
  
  
  
  
  

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %></br>

<div class="row">
	<div class="col-md-offset-3 col-md-8">
	  <div class="box panel panel-default">	  
		  <%= image_tag @pin.image.url(:medium) %>  
			<div class="pin-panel">  
			  <p><%= @pin.description %></p>
			  <strong><%= @pin.user.email if @pin.user %></strong></br>
			  <% if @pin.user == current_user && user_signed_in? %>
				<%= link_to edit_pin_path(@pin) do%> 
				  <span class="glyphicon glyphicon-wrench"></span> Edit
				<% end %>
			    <%= link_to @pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
			      <span class="glyphicon glyphicon-trash", id="remove-glyphicon"></span>Remove
			    <% end %>	
			  <% end %>	
			</div>  
	  </div>	  
	</div>  
</div>   
  